// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monolithic.Api.Modules.Platform.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monolithic.Api.Migrations.PlatformDb
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260227154127_InitialPlatformSchema")]
    partial class InitialPlatformSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.FeatureFlags.Domain.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Scope", "BusinessId", "UserId")
                        .IsUnique();

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.Notifications.Domain.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TemplateSl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "CreatedAtUtc");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.Templates.Domain.TemplateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableVariables")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Scope", "BusinessId", "UserId")
                        .IsUnique();

                    b.ToTable("TemplateDefinitions");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.Templates.Domain.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlainTextFallback")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateDefinitionId");

                    b.ToTable("TemplateVersions");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.Themes.Domain.ThemeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BorderRadiusFull")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderRadiusLg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderRadiusMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderRadiusSm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorAccent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ColorAccentDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorBackgroundDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorBorder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorBorderDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorDanger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorDangerDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorInfoDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorPrimary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ColorPrimaryDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorSecondary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ColorSecondaryDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorSuccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSuccessDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorSurface")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSurfaceDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorTextDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorTextMuted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorTextMutedDark")
                        .HasColumnType("text");

                    b.Property<string>("ColorWarning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorWarningDark")
                        .HasColumnType("text");

                    b.Property<string>("ContentMaxWidth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtensionTokensJson")
                        .HasColumnType("text");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FontFamilyMono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FontScaleRatio")
                        .HasColumnType("numeric");

                    b.Property<string>("FontSizeBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LogoColorsExtractedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LogoColorsOverridden")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoExtractedColorsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShadowLg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShadowMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShadowSm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SidebarPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SidebarWidth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpacingUnit")
                        .HasColumnType("integer");

                    b.Property<string>("TopbarHeight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "Name")
                        .IsUnique();

                    b.ToTable("ThemeProfiles");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.UserPreferences.Domain.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorScheme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DashboardLayoutJson")
                        .HasColumnType("text");

                    b.Property<int>("DefaultPageSize")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredLocale")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PreferredThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferredTimezone")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("PushNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmsNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BusinessId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.Templates.Domain.TemplateVersion", b =>
                {
                    b.HasOne("Monolithic.Api.Modules.Platform.Templates.Domain.TemplateDefinition", "Definition")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Monolithic.Api.Modules.Platform.Templates.Domain.TemplateDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
