namespace Monolithic.Api.Modules.Business.Domain;

/// <summary>
/// Identifies the originating subsystem that generated the journal entry.
/// Manual = human-keyed; others are system-generated from sub-ledgers.
/// </summary>
public enum JournalEntrySourceType
{
    /// <summary>Manually keyed by an accountant.</summary>
    Manual = 0,

    /// <summary>Auto-generated from the Accounts Payable sub-ledger (vendor bills / payments).</summary>
    AccountsPayable = 1,

    /// <summary>Auto-generated from the Accounts Receivable sub-ledger.</summary>
    AccountsReceivable = 2,

    /// <summary>Auto-generated from an inventory valuation or cost adjustment.</summary>
    Inventory = 3,

    /// <summary>Auto-generated from payroll processing.</summary>
    Payroll = 4,

    /// <summary>Auto-generated by a period-end closing routine.</summary>
    PeriodClose = 5,

    /// <summary>Bank reconciliation entry.</summary>
    BankReconciliation = 6,

    /// <summary>Depreciation or amortization run.</summary>
    Depreciation = 7,

    /// <summary>Opening balance entry (system migration).</summary>
    OpeningBalance = 8
}
